### PR TITLE
Automatic multi-arch Docker build

### PR DESCRIPTION
**Pull request by blindmuraqib**

### CODE REVIEW

**Comment by olesenm** [comment]
For the amd64 builds, could actually consider starting from an existing docker image instead: https://develop.openfoam.com/packaging/containers

The arm64 is not quite so straightforward, since the OpenFOAM builds on Ubuntu arm64 have been too slow to put into normal production. However, there are openSUSE rpms for arm64 that are easily leveraged for making images quickly. See the same link for recipes.

**Review by olesenm — COMMENTED** [review]
The openfoam2106-dev or even the openfoam-dev package should be enough (probably don't need any openfoam tutorials).

**Comment by moaadkhamlich** [comment]
I have changed the openfoam container for the amd version. For what concerns the arm, I will explore the possibility of using OpenSuse. However building the container wil still require a lot of time by means of GitHub action because of the compilation phase of ITHACA-FV.

**Comment by blindmuraqib** [comment]
> For the amd64 builds, could actually consider starting from an existing docker image instead: https://develop.openfoam.com/packaging/containers
> 
> The arm64 is not quite so straightforward, since the OpenFOAM builds on Ubuntu arm64 have been too slow to put into normal production. However, there are openSUSE rpms for arm64 that are easily leveraged for making images quickly. See the same link for recipes.

@olesenm 

I have changed the openfoam container for the amd version. For what concerns the arm, I will explore the possibility of using OpenSuse. However building the container wil still require a lot of time by means of GitHub action because of the compilation phase of ITHACA-FV.
Thanks for the comments!

**Pull request merged**
