### PR TITLE
ENH: made library compatible with OF2012

### PR DESCRIPTION
**Pull request by giovastabile**
Fixed the issues with the new implementation of autoPtr.

Main change is to replace snippets of this type:

PtrList<T> list;
T obectI;
list.append(obectI);

with:

PtrList<T> list;
T obectI;
list.append(tmp<T>(obectI));

### CODE REVIEW

**Comment by olesenm** [comment]
This looks like too much work involved. In one of the cases (for example) `inputField` is being passed in parameter, internally assigned from a reconstruct (ie, a tmp) but then created a tmp out of it again (essentially a shallow reference), the append() of that tmp should effect a clone, but the original value is unimportant (discarded on the next loop).

**Comment by giovastabile** [comment]
> This looks like too much work involved. In one of the cases (for example) `inputField` is being passed in parameter, internally assigned from a reconstruct (ie, a tmp) but then created a tmp out of it again (essentially a shallow reference), the append() of that tmp should effect a clone, but the original value is unimportant (discarded on the next loop).

Hi @olesenm I was suspecting that this was not the best to solve the issue and I waited to close the PR because I wanted to ask your opinion. You were faster than me. 

Compiling with OF2012 I had issues in implicit conversion between T and tmp<T> in the append and set method of the PtrList class. I guess it is due to the new implementation with refPtr. How do you think is better to change it?

**Comment by olesenm** [comment]
@giovastabile - nothing to do with refPtr at all.
First need to ask yourself what you are trying to achieve, and from the answers, should guide the solution. I'm just working from memory at the moment about what your code looks like.
If you have a PtrList, you normally populate it yourself with pointers, or things that wrap pointers. Eg, autoPtr, unique_ptr, and to a certain extent tmp. If something such as fvc::reconstruct returns a tmp, just use it. The PtrList append method is a convenience, but since you already know the size of your list, dimension it and use the `set()` method for each index. This saves unneeded allocs/resize each step. Finally, if you _do_ want to return a copy of the last entry in the PtrlList (which is what your parameter passing appears to be??), then do that after setting up the PtrList.

**Comment by giovastabile** [comment]
@olesenm, I will try to explain one case where I use a PtrList.

In many cases, there is the need to store a list of Fields. For example when computing the solution for a parametric problem one needs to create a list of snapshots that contain all the different solutions for different time and parameter values. I will show an example of the velocity field. 

The class for an unsteady parametric Navier-Stokes problem has a member:

PtrList<volVectorField> Ufield;

that during the solution procedure is populated with the volVectorField U; In this case, the dimension is not known a priori and one needs to create a copy of U which keeps changing during the solution procedure.

With the previous versions of OF this was done with the command:

Ufield.append(U);

with the newer version of OpenFOAM, this command is not compiling due to the following error:

call of overloaded ‘append(Foam::volVectorField&)’ is ambiguous Ufield.append(U)

I think that the issue with refPtr is here. Before the compiler was doing an implicit conversion from volVectorField to tmp<volVectorField> which now, due to the additional implementation of append with also refPtr is not able to do. (am I right?)

To make the code compiling and running I changed:

Ufield.append(U); -> Ufield.append(tmp<volVectorField(U));  (Is this the best way?)

In other cases, I know the dimension in advance and I could change the append with a set command.

**Comment by olesenm** [comment]
Ok, I stand corrected it _is_ the additional append with refPtr that makes it ambiguous and thus cannot find an implicit conversion. IMO this is actually a good thing, since implicit conversions in the case are a bit weird anyhow.

I would probably use the following
```
Ufield.append(U.clone());
```

This removes the ambiguity since the clone() method in this case returns a tmp (in a few other classes it returns an autoPtr) that fits perfectly to your needs. It is obviously less typing than what you did have, but most importantly it conveys directly what you mean. Ie, "I want a copy (clone) of this field appended to my list" - which makes it easy to understand and maintain in the future.  

BTW: in some places you might find a PtrDynList works well, but unfortunately only with OpenFOAM-v1806 and later.

Also scanning again through some of the code, you have numerous places where a reference is being passed in a parameter list, when a const reference would do. Other places (eg, fvScalarMatrix) that are being passed as copy instead of const ref for creating Eigen3 content etc.  Should probably pick this up on gitlab, in the New Year.

**Comment by giovastabile** [comment]
@olesenm Thanks for the hint, I have changed the code according to your suggestion and merged the pull request. In the next days, I will also have a look at the other things. In many places, a const ref would be much better than a standard ref or a copy, I will try to change them whenever is possible.

**Comment by giovastabile** [comment]
@olesenm Now I remembered why I used a pass by value option instead of a const ref option.

On the contrary to OF1812 and later versions the fvMatrix class in OF6 does not have a const implementation of the internalCoeffs() method. Therefore, it is not possible to call a non-const method from a const object and I have to stick with the pass by value option (but there might be other options that I am not aware of).

**Pull request merged**
